from __future__ import annotations

import json
import os

from ragin.core.registry import registry

_ENTRY_TEMPLATES: dict[str, str] = {
    "aws": """\
# Auto-generated by `ragin build --provider aws`
from ragin.runtime.aws import AWSProvider
import {module}  # noqa: F401

lambda_handler = {module}.app.get_handler(AWSProvider())
""",
    "gcp": """\
# Auto-generated by `ragin build --provider gcp`
from ragin.runtime.gcp import GCPProvider
import {module}  # noqa: F401

_provider = GCPProvider()

def http_handler(request):
    return {module}.app.handle(request, provider=_provider)
""",
    "azure": """\
# Auto-generated by `ragin build --provider azure`
from ragin.runtime.azure import AzureProvider
import azure.functions as func
import {module}  # noqa: F401

_provider = AzureProvider()

def http_trigger(req: func.HttpRequest) -> func.HttpResponse:
    return {module}.app.handle(req, provider=_provider)
""",
}


def build_app(
    app,
    output_dir: str = "build",
    provider: str = "aws",
    module: str = "main",
) -> None:
    os.makedirs(output_dir, exist_ok=True)
    routes = registry.get_routes()

    # routes.json — describes routes independently of the cloud provider
    routes_data = {
        "provider": provider,
        "entry_point": "_ragin_entry",
        "routes": [{"method": r.method, "path": r.path} for r in routes],
    }
    routes_path = os.path.join(output_dir, "routes.json")
    with open(routes_path, "w", encoding="utf-8") as f:
        json.dump(routes_data, f, indent=2)

    # provider-specific entry point
    template = _ENTRY_TEMPLATES.get(provider)
    if template is None:
        raise ValueError(f"Unknown provider {provider!r}. Valid: {list(_ENTRY_TEMPLATES)}")

    entry_path = os.path.join(output_dir, "_ragin_entry.py")
    with open(entry_path, "w", encoding="utf-8") as f:
        f.write(template.format(module=module))

    print(f"Build output → {output_dir}/")
    print(f"Provider     : {provider}")
    print(f"Routes ({len(routes)}):")
    for r in routes:
        print(f"  {r.method:<7} {r.path}")
