from __future__ import annotations

import json
import os

from ragin.core.registry import registry

_ENTRY_TEMPLATES: dict[str, str] = {
    "aws": """\
# Auto-generated by `ragin build --provider aws`
from ragin.runtime.aws import AWSProvider
import {module}  # noqa: F401

lambda_handler = {module}.app.get_handler(AWSProvider())
""",
    "gcp": """\
# Auto-generated by `ragin build --provider gcp`
from ragin.runtime.gcp import GCPProvider
import {module}  # noqa: F401

_provider = GCPProvider()

def http_handler(request):
    return {module}.app.handle(request, provider=_provider)
""",
    "azure": """\
# Auto-generated by `ragin build --provider azure`
from ragin.runtime.azure import AzureProvider
import azure.functions as func
import {module}  # noqa: F401

_provider = AzureProvider()

def http_trigger(req: func.HttpRequest) -> func.HttpResponse:
    return {module}.app.handle(req, provider=_provider)
""",
}

_MCP_ENTRY_TEMPLATE = """\
# Auto-generated by `ragin build`
import json
from ragin.mcp.server import MCPServer
from ragin.core.registry import registry
import {module}  # noqa: F401

all_tools = registry.get_all_tools()
mcp = MCPServer(all_tools)


def lambda_handler(event, context=None):
    body = json.loads(event.get("body", "{{}}"))
    result = mcp.handle(body)
    return {{
        "statusCode": 200,
        "headers": {{"Content-Type": "application/json"}},
        "body": json.dumps(result),
    }}
"""


def build_app(
    app,
    output_dir: str = "build",
    provider: str = "aws",
    module: str = "main",
) -> None:
    os.makedirs(output_dir, exist_ok=True)
    routes = registry.get_routes()

    # Separate CRUD routes from agent routes
    crud_routes = [r for r in routes if r.operation != "agent"]
    agent_routes = [r for r in routes if r.operation == "agent"]
    has_agents = len(agent_routes) > 0

    # routes.json
    routes_data: dict = {
        "provider": provider,
        "lambdas": {
            "crud": {
                "entry_point": "_ragin_entry",
                "routes": [{"method": r.method, "path": r.path} for r in crud_routes],
            },
        },
    }
    if has_agents:
        routes_data["lambdas"]["agent"] = {
            "entry_point": "_ragin_entry",
            "routes": [{"method": r.method, "path": r.path} for r in agent_routes],
        }
        routes_data["lambdas"]["mcp"] = {
            "entry_point": "_ragin_mcp_entry",
            "routes": [{"method": "POST", "path": "/mcp"}],
        }

    routes_path = os.path.join(output_dir, "routes.json")
    with open(routes_path, "w", encoding="utf-8") as f:
        json.dump(routes_data, f, indent=2)

    # provider-specific CRUD + agent entry point
    template = _ENTRY_TEMPLATES.get(provider)
    if template is None:
        raise ValueError(f"Unknown provider {provider!r}. Valid: {list(_ENTRY_TEMPLATES)}")

    entry_path = os.path.join(output_dir, "_ragin_entry.py")
    with open(entry_path, "w", encoding="utf-8") as f:
        f.write(template.format(module=module))

    # MCP entry point (if agents are registered)
    if has_agents:
        mcp_path = os.path.join(output_dir, "_ragin_mcp_entry.py")
        with open(mcp_path, "w", encoding="utf-8") as f:
            f.write(_MCP_ENTRY_TEMPLATE.format(module=module))

    print(f"Build output → {output_dir}/")
    print(f"Provider     : {provider}")
    print(f"Routes ({len(routes)}):")
    for r in routes:
        print(f"  {r.method:<7} {r.path}")
