"""
Base interface for LLM providers.

Every provider must implement complete() — a single method that sends messages
to the LLM and returns a response with optional tool calls.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class ToolCall:
    """A single tool call requested by the LLM."""

    id: str                       # unique identifier (generated by the LLM)
    name: str                     # tool function name
    arguments: dict[str, Any]     # parsed arguments

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "type": "function",
            "function": {
                "name": self.name,
                "arguments": self.arguments,
            },
        }


@dataclass
class AgentResponse:
    """Response from the LLM provider."""

    content: str | None = None
    tool_calls: list[ToolCall] = field(default_factory=list)


class BaseProvider:
    """
    Abstract base for LLM providers.

    Subclasses must implement complete().
    The provider converts internally from/to the native LLM format.
    """

    def complete(
        self,
        messages: list[dict],
        tools: list[dict] | None = None,
    ) -> AgentResponse:
        """
        Send messages to the LLM and return the response.

        messages: OpenAI-style message list
            [{"role": "system", "content": "..."}, {"role": "user", "content": "..."}, ...]

        tools: OpenAI function-calling tool schemas
            [{"type": "function", "function": {"name": ..., "parameters": ...}}]

        Returns AgentResponse with content (final answer) or tool_calls (needs execution).
        """
        raise NotImplementedError
